package com.rccs.docgen.enums;

public enum HeaderType {
	WITHOUT_HEADER("SIN_CABECERA"), //T1, T5, T10
	REQUEST_ORIGIN("ORIGEN_DE_LA_SOLICITUD"),//T2
	FILE_VALIDATION("VALIDACION_DE_ARCHIVOS"),//T3
	PREREQUISITES("PREREQUISITOS"),//T4
	FILE_LOCATION("UBICACION_DE_ARCHIVOS"),//T6
	ENVIRONMENT_CONFIG("CONFIGURACION_DE_AMBIENTES"),//T7
	ARTIFACT_INSTALLATION("INSTALACION_DE_ARTEFACTOS"),//T8
	DELIVERY_INFO("DATOS_DE_LA_LIVERACION"),//T9
	DB_SCRIPT("SCRIPTS_DE_BASE_DE_DATOS"),//T11
	DB_REVERSE_SCRIPT("SCRIPTS_DE_REVERSO_DE_BASE_DE_DATOS"),//T12
	DOC_VERSION("VERSIONES_DEL_DOCUMENTO");//T13
	
	
	private final String type;
	
	private HeaderType(String type) {
		this.type = type;
	}
	
	public String getType() {
		return type;
	}
	
}
